# Dockerfile.prod

# FROM tiangolo/uvicorn-gunicorn:python3.11-slim
FROM tedivm/uvicorn-gunicorn

RUN apt-get update && apt-get install -y netcat-traditional

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

